#!/usr/bin/env bash
# Displays a list of currently running processes.
#   Shows all processes, for all users, including those
#+  which might not have a TTY.

# Display headers
printf "%-10s %-6s %-6s %-6s %-6s %-6s %-10s %-4s %-8s %-10s\n" \
	"USER" "PID" "%CPU" "%MEM" "VSZ" "RSS" "TTY" "STAT" "START" "TIME" "COMMAND"

# Display process information
ps aux --forest | tail -n +2
